### ISSUE TITLE
background color change ?

### ISSUE THREAD

**Issue by Tecktorious** [kibook/poodlechat#9]
wheres the file to change the background ?

**Comment by kibook** [comment]
You can edit the files in the [html](https://github.com/kibook/poodlechat/tree/master/html) folder to change the style of things, particularly [index.css](https://github.com/kibook/poodlechat/blob/master/html/index.css). You can also in theory create a chat theme resource like [the one included in cfx-server-data](https://github.com/citizenfx/cfx-server-data/tree/master/resources/%5Bgameplay%5D/chat-theme-gtao) to modify the look without modifying the base resource. Themes written for the base cfx chat resource may not completely work for poodlechat since it adds a few new elements to the UI (like the channel list).
